[project]
name = "todo-backend"
version = "0.1.0"
description = "Backend for todo application"
authors = [
    {name = "Developer", email = "developer@example.com"}
]
dependencies = [
    "fastapi>=0.110.0",
    "sqlmodel>=0.0.17",
    "uvicorn>=0.29.0",
    "psycopg2-binary>=2.9.0",
    "psycopg[binary]>=3.3.2",
    "pydantic-settings>=2.12.0"
]
readme = "README.md"
requires-python = ">=3.14"

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"